spring.application.name=auth-service

server.port=9000

eureka.client.service-url.defaultzone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true


spring.datasource.url=jdbc:postgresql://ep-shiny-butterfly-aomn842u-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_WpR9wCh4zoSj&sslmode=require&channelBinding=require
spring.jpa.hibernate.ddl-auto=update


clientUrl=https://smart-attend-ai.netlify.app

jwt.secret=ThisIsMyVeryStrongJWTSecretKeyForFaceTrack2026
jwt.issuer=FaceTrack
####### 15 min  ########
jwt.access-token-expiration=900000
####### 15 days ########
jwt.refresh-token-expiration=1296000000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=harishkamavaram0007@gmail.com
spring.mail.password=djyn vriu fuzo dxpf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


spring.data.redis.host=splendid-shrew-86901.upstash.io
spring.data.redis.port=6379
spring.data.redis.username=default
spring.data.redis.password=gQAAAAAAAVN1AAIgcDIzNmMzMWVmZmNhMjc0NWQ4YWE0MjM4ZGY4YTI0NjI3Mw
spring.data.redis.ssl.enabled=true
