spring.application.name=api-gateway

server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

logging.level.org.springframework.cloud.gateway=TRACE
#This enables all Spring Boot Actuator endpoints over HTTP
management.endpoints.web.exposure.include=*


eureka.instance.prefer-ip-address=true

jwt.secret=ThisIsMyVeryStrongJWTSecretKeyForFaceTrack2026