spring.application.name=api-gateway
server.port=8080

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Register Gateway with localhost instead of WSL IP
eureka.instance.hostname=localhost
eureka.instance.ip-address=127.0.0.1
eureka.instance.prefer-ip-address=false

# Gateway Discovery Locator
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.routes[0].id=image-service
spring.cloud.gateway.routes[0].uri=https://harishkamavaram--smart-attendance-image-service-fastapi-app.modal.run
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/images/**

spring.cloud.gateway.routes[1].id=face-recognition
spring.cloud.gateway.routes[1].uri=https://harishkamavaram--smart-attendance-ai-fastapi-app.modal.run
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/fr/**
#spring.cloud.gateway.routes[1].filters[0]=SetRequestHeader=Host,harishkamavaram--smart-attendance-ai-fastapi-app.modal.run

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.gateway.access=unrestricted

# Logging
logging.level.org.springframework.cloud.gateway=TRACE
logging.level.org.springframework.cloud.loadbalancer=TRACE
logging.level.com.netflix.discovery=DEBUG

# JWT
jwt.secret=ThisIsMyVeryStrongJWTSecretKeyForFaceTrack2026